# Page text for site-src/template.html, one table per language.
# Every key must exist in both tables; scripts/build-site.py refuses a gap.
# Values may hold inline HTML. Keep commands, station names, file names and
# flags in English in both languages.

SITE = "https://daskinnyman.github.io/granada-release/"

EN = {
    "title": "Granada",
    "meta_description": "Granada is a host-native software factory: a one-line intent in, a merge-ready draft pull request out, run by the coding agent already in your CLI (Claude Code, Codex or Cursor).",
    "og_locale": "en_US",
    "og_title": "Granada: one-line intent in, draft pull request out",
    "og_description": "A host-native software factory run by the coding agent already in your CLI: Claude Code, Codex or Cursor.",
    "prompt_link_title": "Agent setup prompt",
    "font_extra": "",
    "js_copied": "Copied",
    "js_copy_failed": "Select and copy",
    "skip": "Skip to content",
    "tb_project": "Project",
    "tb_release": "Release",
    "tb_sheet": "Sheet",
    "nav_label": "Sections",
    "nav_how": "How it works",
    "nav_tracks": "Tracks",
    "nav_setup": "Agent setup",
    "nav_install": "Install",
    "hero_sheet": "Sheet 01 · General arrangement",
    "hero_tag": "host-native software factory",
    "hero_sub": "Intent → draft pull request",
    "hero_lede": "You type one line. The coding agent already in your CLI (<b>Claude Code</b>, <b>Codex</b> or <b>Cursor</b>) takes it down a fixed track of stations. At the end of the track is a merge-ready draft pull request.",
    "cta_setup": "Set up with your agent",
    "cta_install": "Install by hand",
    "x_rim": "crater rim · factory city inside",
    "x_depth": "depth",
    "x_a": "A · tool stations",
    "x_a2": "worktree, tests, ship, merge",
    "x_b": "B · agent stations",
    "x_b2": "your host agent thinks here",
    "x_c": "C · the track",
    "x_c2": "fixed order, checked answers",
    "what_no": "Sheet 02 · What it is",
    "what_h": "One line in. A draft pull request out.",
    "what_sub": "Granada is a CLI that your coding agent drives. It does not bring its own model. The agent you already use does the thinking, and Granada keeps the work on a fixed track.",
    "flow1_k": "You type",
    "flow2_k": "The track runs",
    "flow2": "Spec, review, plan, build in a worktree, test, review, check. You answer a few questions in chat.",
    "flow3_k": "You get",
    "flow3": "A draft pull request on <code>granada/&lt;change-id&gt;--&lt;run-id&gt;</code> and one decision page in plain words.",
    "role1_h": "Granada owns the track",
    "role1": "Which station comes next, what each station must hand back, and the checks every answer has to pass. It records the run.",
    "role2_h": "Your agent does the thinking",
    "role2": "At each agent station, the agent in Claude Code, Codex or Cursor writes the answer. An answer that fails its check goes back to the agent.",
    "role3_h": "Tool stations run on their own",
    "role3": "Worktree, tests, ship checks, quality, mutation, drift, merge and forge. Granada runs these itself.",
    "video_file": "granada-intro-en.mp4",
    "video_poster": "granada-intro-en.jpg",
    "video_label": "Granada introduction video",
    "video_fallback": "Download the introduction video (MP4)",
    "video_caption": "Fig. 02-A · Granada in one minute · 62 s, narrated, with subtitles",
    "how_no": "Sheet 03 · How it works",
    "how_h": "The feature track, station by station.",
    "how_sub": "A track is a YAML manifest. The feature track has 28 stations. Each one takes the work one step on. The line lights up as you scroll.",
    "how_list_label": "Feature track stations",
    "key_agent": "agent station",
    "key_tool": "tool station",
    "key_human": "you decide here",
    "key_off": "off by default (ui)",
    "small_h": "Small changes run lighter",
    "small": "When sizing estimates at most 5 files, 200 changed lines and 2 requirements, the run leaves out amigos, synthesizer, spec-revise and plan-review. You still approve the spec. If the built change is larger, the run goes back and runs every station.",
    "block_h": "When a station blocks",
    "block": "The agent tells you why. Fix what it names, then continue from that station:",
    "tracks_no": "Sheet 04 · Tracks",
    "tracks_h": "Three tracks ship with Granada.",
    "tracks_sub": "Each track starts from one command in your host CLI. The dot marks a station where you answer in chat.",
    "t_feature": "Works on a spec in the framework your repository uses, or a short markdown spec when it uses none. It proposes the spec, reviews it, and builds it in a worktree.",
    "t_patch": "Fixes one bug. <b>triage</b> settles the scope and a reproduction script with you. <b>reproduce</b> must see the bug before anything is fixed. The pull request title starts with <code>fix:</code>.",
    "t_bootstrap": "Creates a project from nothing, or a scaffold on its own branch in an existing repository. A large project is split into a runnable skeleton and follow-up features that you start later.",
    "t_stations": "Stations",
    "t_off": "Off by default",
    "t_none": "none",
    "decide_no": "Sheet 05 · You stay in charge",
    "decide_h": "Every decision gets one page.",
    "decide_sub": "The track stops for you at a few points: clarify, sizing and the readable spec on a feature run, triage on a patch, the charter and the architecture on a bootstrap. The agent shows you the page before it asks for your answer.",
    "decide_sub2": "After the build, <b>change-brief</b> writes the same kind of page for the whole change. To make the run stop there for your answer:",
    "page_label": "The parts of a decision page, in order",
    "pg1": "The decision and its risk",
    "pg2": "The change in plain words",
    "pg3": "Why it is made",
    "pg4": "What it touches",
    "pg5": "The change in the order it is built",
    "pg6": "The words it uses, explained",
    "page_caption": "Decision page · layout, not to scale",
    "setup_no": "Sheet 06 · Agent setup",
    "setup_h": "Let your agent set it up.",
    "setup_sub": "Paste one line into your agent, in the repository where you want Granada. The agent reads the steps and runs them: Node check, install, host sync, host doctor. It asks you before it commits.",
    "one_liner": "Read https://daskinnyman.github.io/granada-release/setup-prompt.md and follow it.",
    "copy_line": "Copy line",
    "tabs_label": "Host CLI",
    "tab_claude": "Start Claude Code in your repository and paste the line. After sync, Claude Code may ask you to approve the granada MCP server. Approve it.",
    "tab_codex": "Start Codex in your repository and paste the line. Sync writes .codex/config.toml and .codex/hooks.json for Codex.",
    "tab_cursor": "Open your repository in Cursor and paste the line into the agent chat. Sync writes .cursor/mcp.json for Cursor.",
    "tab_default": "Start your host CLI in your repository and paste the line. Claude Code, Codex and Cursor all work.",
    "full_intro": "If your agent cannot fetch web pages, paste the full prompt instead:",
    "full_label": "setup-prompt.md · full text",
    "copy_prompt": "Copy prompt",
    "install_no": "Sheet 07 · Manual install",
    "install_h": "Install by hand.",
    "req": "Required",
    "opt": "Optional",
    "req_node": "Granada is a Node CLI. You need Node also when you install with Homebrew or curl.",
    "req_git_h": "A git repository",
    "req_git": "Bootstrap can start from an empty folder, after <code>git init</code>.",
    "req_host_h": "One host CLI",
    "req_gh": "For GitHub draft pull requests.",
    "copy": "Copy",
    "brew_note": "Update with <code>brew upgrade granada</code> (or <code>granada update</code>).",
    "curl_note": "Puts <code>granada</code> on PATH at <code>~/.local/bin</code>. Add that directory to PATH if the command is not found. Pin a version with <code>GRANADA_VERSION=&lt;version&gt;</code>.",
    "sync_h": "Connect your host",
    "sync_note": "Run these in your repository. Sync writes the skills, the MCP server entry and the Stop hook. Doctor checks that the host sees them. Commit the files that sync wrote.",
    "run_h": "Run a track",
    "run_note": "Start your host CLI in the repository and type one of these.",
    "openspec_h": "OpenSpec: only if your repository uses it.",
    "openspec": "Plain markdown specs, Granada's default, need nothing installed. A repository that writes its specs with OpenSpec needs version 1.13.0 or newer, installed globally so the host finds it:",
    "mutation_h": "Mutation in a Node project.",
    "mutation": "The feature track runs a mutation station by default. It needs <code>@stryker-mutator/core</code> as a devDependency, committed on the base branch. <code>granada run start</code> names the command to add it. You can also turn mutation off with <code>mutation: { enabled: false }</code> in Granada's <code>gates.yaml</code>.",
    "foot_nod": "Named after a lunar crater city that builds machines.",
    "foot_links": "Links",
    "foot_repo": "Release repository",
    "foot_releases": "Releases",
    "foot_other": "繁體中文版",
    "foot_build": "Build",
    "foot_version": "Version",
    "hint_text": "這個頁面有繁體中文版。",
}

ZH = {
    "title": "Granada（繁體中文）",
    "meta_description": "Granada 是在你的 CLI 裡執行的軟體工廠：輸入一行需求，產出可合併的 draft pull request，由你已在使用的 AI 程式代理（Claude Code、Codex 或 Cursor）執行。",
    "og_locale": "zh_TW",
    "og_title": "Granada：輸入一行需求，產出 draft pull request",
    "og_description": "由你 CLI 裡的 AI 程式代理（Claude Code、Codex 或 Cursor）執行的軟體工廠。",
    "prompt_link_title": "代理安裝提示詞",
    "font_extra": "&family=Noto+Sans+TC:wght@300;400;600",
    "js_copied": "已複製",
    "js_copy_failed": "請手動選取複製",
    "skip": "跳到主要內容",
    "tb_project": "專案",
    "tb_release": "版本",
    "tb_sheet": "圖號",
    "nav_label": "章節",
    "nav_how": "運作方式",
    "nav_tracks": "產線",
    "nav_setup": "代理安裝",
    "nav_install": "手動安裝",
    "hero_sheet": "圖 01 · 總配置圖",
    "hero_tag": "在你的 CLI 裡執行的軟體工廠",
    "hero_sub": "需求 → draft pull request",
    "hero_lede": "你輸入一行需求。你 CLI 裡已有的 AI 程式代理（<b>Claude Code</b>、<b>Codex</b> 或 <b>Cursor</b>）帶著它走過一條固定的工作站產線。產線的終點是一個可合併的 draft pull request。",
    "cta_setup": "讓代理幫你安裝",
    "cta_install": "手動安裝",
    "x_rim": "隕石坑外緣 · 內有工廠城市",
    "x_depth": "深度",
    "x_a": "A · 工具工作站",
    "x_a2": "worktree、測試、ship、merge",
    "x_b": "B · 代理工作站",
    "x_b2": "由你的代理思考",
    "x_c": "C · 產線",
    "x_c2": "固定順序，每個答案都要通過檢查",
    "what_no": "圖 02 · 這是什麼",
    "what_h": "輸入一行，產出一個 draft PR。",
    "what_sub": "Granada 是一個由你的 AI 程式代理操作的 CLI。它不自帶模型。思考由你已在使用的代理負責，Granada 讓工作沿著固定的產線前進。",
    "flow1_k": "你輸入",
    "flow2_k": "產線執行",
    "flow2": "撰寫規格、審查、規劃、在 worktree 中實作、測試、審查、檢查。過程中你在對話裡回答幾個問題。",
    "flow3_k": "你得到",
    "flow3": "在 <code>granada/&lt;change-id&gt;--&lt;run-id&gt;</code> 分支上的 draft pull request，以及一頁用白話寫的決策頁。",
    "role1_h": "Granada 掌管產線",
    "role1": "決定下一個工作站、每個工作站必須交回什麼，以及每個答案必須通過的檢查。它會記錄整個執行過程。",
    "role2_h": "你的代理負責思考",
    "role2": "在每個代理工作站，Claude Code、Codex 或 Cursor 裡的代理寫出答案。沒通過檢查的答案會退回給代理。",
    "role3_h": "工具工作站自動執行",
    "role3": "worktree、測試、ship 檢查、品質、mutation、drift、merge 和 forge。這些由 Granada 自己執行。",
    "video_file": "granada-intro-zh.mp4",
    "video_poster": "granada-intro-zh.jpg",
    "video_label": "Granada 介紹影片",
    "video_fallback": "下載介紹影片（MP4）",
    "video_caption": "圖 02-A · 一分鐘認識 Granada · 69 秒，含旁白與字幕",
    "how_no": "圖 03 · 運作方式",
    "how_h": "feature 產線，逐站說明。",
    "how_sub": "每條產線都是一份 YAML manifest。feature 產線有 28 個工作站，每一站把工作往前推進一步。往下捲動時，產線會一站一站亮起來。",
    "how_list_label": "feature 產線的工作站",
    "key_agent": "代理工作站",
    "key_tool": "工具工作站",
    "key_human": "由你決定",
    "key_off": "預設關閉（ui）",
    "small_h": "小改動跑得更輕",
    "small": "當 sizing 估計最多 5 個檔案、200 行變更、2 項需求時，這次執行會略過 amigos、synthesizer、spec-revise 和 plan-review。規格仍然要由你核准。如果實際做出來的改動比估計大，執行會退回去，把每個工作站都跑一遍。",
    "block_h": "工作站卡住時",
    "block": "代理會告訴你原因。修正它指出的問題後，從那個工作站繼續：",
    "tracks_no": "圖 04 · 產線",
    "tracks_h": "Granada 內建三條產線。",
    "tracks_sub": "每條產線都從主機 CLI 裡的一個指令開始。圓點代表你要在對話中回答的工作站。",
    "t_feature": "依照儲存庫使用的規格框架撰寫規格；如果沒有使用任何框架，就寫一份簡短的 markdown 規格。它提出規格、審查規格，然後在 worktree 中實作。",
    "t_patch": "修正一個 bug。<b>triage</b> 會和你確認範圍和重現腳本。<b>reproduce</b> 必須先重現 bug，才會開始修正。pull request 標題以 <code>fix:</code> 開頭。",
    "t_bootstrap": "從零建立一個專案，或在既有儲存庫的獨立分支上建立骨架。大型專案會拆成一個可執行的骨架，加上之後由你啟動的後續功能。",
    "t_stations": "工作站數",
    "t_off": "預設關閉",
    "t_none": "無",
    "decide_no": "圖 05 · 決定權在你",
    "decide_h": "每個決定都只看一頁。",
    "decide_sub": "產線會在幾個點停下來等你：feature 的 clarify、sizing 和 readable spec，patch 的 triage，bootstrap 的 charter 和架構。代理會先給你看決策頁，再請你回答。",
    "decide_sub2": "實作完成後，<b>change-brief</b> 會為整個改動寫一頁同樣格式的決策頁。如果要讓執行停在這裡等你回答：",
    "page_label": "決策頁的各個部分，依序排列",
    "pg1": "要做的決定和風險",
    "pg2": "用白話說明這個改動",
    "pg3": "為什麼要改",
    "pg4": "會影響哪些地方",
    "pg5": "依實作順序列出的改動",
    "pg6": "用到的術語解釋",
    "page_caption": "決策頁 · 版面示意，非實際比例",
    "setup_no": "圖 06 · 代理安裝",
    "setup_h": "讓你的代理幫你安裝。",
    "setup_sub": "在要使用 Granada 的儲存庫裡，把下面這一行貼給你的代理。代理會讀取步驟並逐一執行：檢查 Node、安裝、host sync、host doctor。提交（commit）前它會先問你。這個版本的提示詞會請代理用繁體中文回覆你。",
    "one_liner": "請讀取 https://daskinnyman.github.io/granada-release/zh/setup-prompt.md 並照著步驟執行。",
    "copy_line": "複製這行",
    "tabs_label": "主機 CLI",
    "tab_claude": "在儲存庫裡啟動 Claude Code，貼上這一行。sync 之後，Claude Code 可能會請你核准 granada MCP server，請核准。",
    "tab_codex": "在儲存庫裡啟動 Codex，貼上這一行。sync 會為 Codex 寫入 .codex/config.toml 和 .codex/hooks.json。",
    "tab_cursor": "在 Cursor 開啟儲存庫，把這一行貼到 agent 對話中。sync 會為 Cursor 寫入 .cursor/mcp.json。",
    "tab_default": "在儲存庫裡啟動你的主機 CLI，貼上這一行。Claude Code、Codex 和 Cursor 都可以。",
    "full_intro": "如果你的代理無法讀取網頁，請改貼完整的提示詞：",
    "full_label": "zh/setup-prompt.md · 全文",
    "copy_prompt": "複製提示詞",
    "install_no": "圖 07 · 手動安裝",
    "install_h": "手動安裝。",
    "req": "必要",
    "opt": "選用",
    "req_node": "Granada 是 Node CLI。用 Homebrew 或 curl 安裝時也需要 Node。",
    "req_git_h": "一個 git 儲存庫",
    "req_git": "bootstrap 可以從空資料夾開始，先執行 <code>git init</code>。",
    "req_host_h": "一個主機 CLI",
    "req_gh": "用來開 GitHub 的 draft pull request。",
    "copy": "複製",
    "brew_note": "用 <code>brew upgrade granada</code>（或 <code>granada update</code>）更新。",
    "curl_note": "把 <code>granada</code> 安裝到 <code>~/.local/bin</code>。如果找不到指令，請把這個目錄加進 PATH。用 <code>GRANADA_VERSION=&lt;version&gt;</code> 指定版本。",
    "sync_h": "連接你的主機",
    "sync_note": "在儲存庫裡執行。sync 會寫入 skills、MCP server 設定和 Stop hook；doctor 會檢查主機是否讀得到它們。請提交 sync 寫入的檔案。",
    "run_h": "執行一條產線",
    "run_note": "在儲存庫裡啟動主機 CLI，輸入其中一個指令。",
    "openspec_h": "OpenSpec：只有儲存庫使用它時才需要。",
    "openspec": "Granada 預設使用一般 markdown 規格，不需要安裝任何東西。用 OpenSpec 撰寫規格的儲存庫需要 1.13.0 或更新版本，並且要全域安裝，主機才找得到：",
    "mutation_h": "Node 專案的 mutation。",
    "mutation": "feature 產線預設會執行 mutation 工作站。它需要把 <code>@stryker-mutator/core</code> 列為 devDependency，並提交到基底分支。<code>granada run start</code> 會列出加入它的指令。也可以在 Granada 的 <code>gates.yaml</code> 設定 <code>mutation: { enabled: false }</code> 關閉 mutation。",
    "foot_nod": "名稱取自一座在月球隕石坑裡製造機械的城市。",
    "foot_links": "連結",
    "foot_repo": "發行儲存庫",
    "foot_releases": "版本列表",
    "foot_other": "English version",
    "foot_build": "版本資訊",
    "foot_version": "版本",
    "hint_text": "這個頁面有繁體中文版。",
}
